# Generated by Django 2.2.24 on 2022-03-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_id',
            field=models.IntegerField(default=0),
        ),
    ]
