# Generated by Django 2.2.24 on 2022-03-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('forProduct', models.ForeignKey(on_delete=None, to='products.Product')),
            ],
        ),
    ]
