# Generated by Django 2.2.24 on 2022-03-17 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hunter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
