# Generated by Django 2.2.24 on 2022-03-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='parent_id',
            field=models.ForeignKey(default=0, on_delete=None, related_name='review', to='products.Review'),
        ),
    ]
