# Generated by Django 2.2.24 on 2022-03-13 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220313_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_id',
            field=models.UUIDField(default=uuid.UUID('b7bda63a-2f9e-4881-a7dc-0cf3344039f0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('607fa0d2-9fda-4abb-b558-9f2440c2fb67'), editable=False),
        ),
    ]
