# Generated by Django 2.2.24 on 2022-03-13 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220313_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review_id',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('5bfcc60c-7fd0-4d16-9521-54682fc65079'), editable=False),
        ),
    ]
