# Generated by Django 2.2.24 on 2022-03-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220313_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
